services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: rit-web
    command: ./start
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
      - compose/postgres/.env.prod.db
    depends_on:
      - postgres

  postgres:
    build:
      context: compose/postgres
      dockerfile: Dockerfile
    image: rit-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_data_backups:/backups
    env_file:
      - compose/postgres/.env.prod.db

  nginx:
    build:
      context: compose/nginx
      dockerfile: Dockerfile
    image: rit-nginx
    ports:
      - "80:80"
    volumes:
        - static_volume:/app/staticfiles
    depends_on:
      - django

volumes:
  postgres_data:
  postgres_data_backups:
  static_volume: