version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rit-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./env.dev