version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: rit-web
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn rit.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_data_backups:/backups
    environment:
      - POSTGRES_USER=TPHxdAHqjBHoZiOeRwEpGoVsnEPuWUgM
      - POSTGRES_PASSWORD=nsIBnEKhc9uqVLsRhWzVLov52JAaSIBFNxi7lXC6iBeHVGJWDRZUnklVnxSI6Dr2
      - POSTGRES_DB=rit_db
#    env_file:
#      - ./env.dev

volumes:
  postgres_data:
  postgres_data_backups:
