services:
  django:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./compose/dev/django/env.dev
      - ./compose/dev/postgres/env.dev
    depends_on:
      - postgres

  postgres:
    build:
        context: .
        dockerfile: ./compose/dev/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=TPHxdAHqjBHoZiOeRwEpGoVsnEPuWUgM
#      - POSTGRES_PASSWORD=nsIBnEKhc9uqVLsRhWzVLov52JAaSIBFNxi7lXC6iBeHVGJWDRZUnklVnxSI6Dr2
#      - POSTGRES_DB=rit_db
    env_file:
      - ./compose/dev/postgres/env.dev

volumes:
  postgres_data:
