# Generated by Django 4.2.13 on 2024-06-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="officer",
            options={"verbose_name": "Oficial", "verbose_name_plural": "Oficiales"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Persona", "verbose_name_plural": "Personas"},
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={"verbose_name": "Vehículo", "verbose_name_plural": "Vehículos"},
        ),
        migrations.AlterModelOptions(
            name="violation",
            options={
                "verbose_name": "Infracción",
                "verbose_name_plural": "Infracciones",
            },
        ),
        migrations.AlterField(
            model_name="officer",
            name="identification_number",
            field=models.BigIntegerField(
                editable=False, unique=True, verbose_name="Número de identificación"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Correo electrónico"),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Nombres"),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Apellidos"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(max_length=50, verbose_name="Marca"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.CharField(max_length=25, verbose_name="Color"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Placa de patente"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.person",
                verbose_name="Dueño/a",
            ),
        ),
        migrations.AlterField(
            model_name="violation",
            name="comments",
            field=models.TextField(verbose_name="Comentarios"),
        ),
        migrations.AlterField(
            model_name="violation",
            name="officer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.officer",
                verbose_name="Oficial",
            ),
        ),
        migrations.AlterField(
            model_name="violation",
            name="timestamp",
            field=models.DateTimeField(verbose_name="Fecha y hora"),
        ),
        migrations.AlterField(
            model_name="violation",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.vehicle",
                verbose_name="Vehículo",
            ),
        ),
    ]
